### ISSUE TITLE
Error update via USB port

### ISSUE THREAD

**Issue by 0l4y4** [greatscottgadgets/yardstick#21]
Hi, 

I am trying to update the yardstick one and I have this problem:

`rfcat --bootloader --force`

```
make installRfCatYS1CCBootloader


==RfCatYS1CCBootloader.hex building==
sdcc -Iinclude -DBUILD_VERSION=`../revision.sh` --xram-loc 0xF000  --code-loc 0x1400 appFHSSNIC.c chipcon_usb.rel chipcon_usbdebug.rel chipcon_dma.rel bootloader.rel cc1111rf.rel global.rel cc1111_aes.rel -DYARDSTICKONE -DCC1111 -DUSBDEVICE
packihx <appFHSSNIC.ihx >bins/RfCatYS1CCBootloader.hex
packihx: read 622 lines, wrote 1199: OK.
if [ ! -c /dev/RFCAT_BL_YS1 ] ; then ../rfcat --bootloader --force -S && sleep 1 ; fi ;
Traceback (most recent call last):
  File "../rfcat", line 11, in <module>
    from rflib import *
  File "/home/ol4y4/rfcat/rflib/__init__.py", line 6, in <module>
    from builtins import str
ImportError: No module named builtins
make: *** [Makefile:378: installRfCatYS1CCBootloader] Error 1
```

**Comment by vsboost** [comment]
pip install future

**Comment by straithe** [comment]
@0l4y4 it looks like a PIP install error. Have you tried again? Have you opened an issue on the RF CAT repository?

**Comment by pickeditmate** [comment]
If you have a greatfet it's trivial to just flash the hex using pogo pins. No need to have the bootloader unless you really want it

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
